<a href="https://colab.research.google.com/github/Shikher-jain/Data_Science/blob/main/DL/PYTORCH/CampusX_PT/Pytorch_CampusX.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [146]:
import torch

In [147]:
print(torch.__version__)

2.11.0+cpu


In [148]:
print(torch.cuda.is_available())

False


In [149]:
if torch.cuda.is_available():
    print(torch.cuda.get_device_name(0))
else:
    print("No GPU available")


No GPU available


In [150]:
torch.empty(2, 3)

tensor([[0.2379, 0.0000, 0.3474],
        [0.0000, 0.0000, 0.0000]])

In [151]:
torch.zeros(2, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [152]:
torch.ones(2, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [153]:
torch.rand(2, 3)

tensor([[0.5741, 0.7075, 0.4120],
        [0.8646, 0.2945, 0.6296]])

In [154]:
torch.manual_seed(101)
torch.rand(2, 3)

tensor([[0.1980, 0.4503, 0.0909],
        [0.8872, 0.2894, 0.0186]])

In [155]:
torch.tensor([[1, 2, 3], [4, 5, 6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [156]:
print(torch.arange(1,11,2))
print(torch.linspace(1,10,4))
print(torch.eye(6))
print(torch.full((2,3),2.4))

tensor([1, 3, 5, 7, 9])
tensor([ 1.,  4.,  7., 10.])
tensor([[1., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 1.]])
tensor([[2.4000, 2.4000, 2.4000],
        [2.4000, 2.4000, 2.4000]])


In [157]:
x = torch.tensor([[1,2,3],[4,5,6]])
x.shape

torch.Size([2, 3])

In [158]:
 torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [159]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [160]:
x.dtype,y.dtype

(torch.int64, torch.float32)

In [161]:
y = torch.tensor([[1,2,3],[4,5,6]],dtype=torch.float64)
y.shape,y.dtype

(torch.Size([2, 3]), torch.float64)

In [162]:
y.to((torch.int32))
x.dtype,y.dtype

(torch.int64, torch.float64)

In [163]:
x.dtype,y.dtype

(torch.int64, torch.float64)

In [164]:
torch.rand_like(x,dtype=torch.float64)

tensor([[0.2764, 0.4473, 0.8208],
        [0.6668, 0.1196, 0.7218]], dtype=torch.float64)

In [165]:
torch.cat((x,x,x), dim=0)

tensor([[1, 2, 3],
        [4, 5, 6],
        [1, 2, 3],
        [4, 5, 6],
        [1, 2, 3],
        [4, 5, 6]])

In [166]:
print("X :" ,x)
print("Y :" ,y)

print("ADD")
print(x+y)
print(torch.add(x,y))
print(x.add(y))

print("SUBTRACT")
print(x-y)
print(torch.sub(x,y))
print(x.sub(y))

print("MULTIPLY")
print(x*y)
print(torch.mul(x,y))
print(x.mul(y))

print("DIVIDE")
print(x/y)
print(torch.div(x,y))
print(x.div(y))

print("POWER")
print(x**y)
print(torch.pow(x,y))
print(x.pow(y))

print("SQRT")
print(torch.sqrt(x))
print(x.sqrt())

print("EXP")
print(torch.exp(x))
print(x.exp())

print("LOG")
print(torch.log(x))
print(x.log())

print("SIN")
print(torch.sin(x))
print(x.sin())

print("COS")
print(torch.cos(x))
print(x.cos())

print("TAN")
print(torch.tan(x))
print(x.tan())

print("ABS")
print(torch.abs(x))
print(x.abs())

print("SUM")
print(torch.sum(x))
print(x.sum())

print("MEAN")
print(torch.mean(y))
print(y.mean())

print("MAX")
print(torch.max(x))
print(x.max())

print("MIN")
print(torch.min(x))
print(x.min())

print("ARGMAX")
print(torch.argmax(x))
print(x.argmax())

print("ARGMIN")
print(torch.argmin(x))
print(x.argmin())

print("EQUAL")
print(torch.eq(x,y))
print(x.eq(y))

print("NOT EQUAL")
print(torch.ne(x,y))
print(x.ne(y))

print("Std")
print(torch.std(y))
print(y.std())

print("Var")
print(torch.var(y))
print(y.var())

print("Transpose")
print(torch.t(x))
print(x.t())

print("Transpose")
print(torch.transpose(x,0,1))
print(x.transpose(0,1))

print("Reshape")
print(torch.reshape(x,(3,2)))
print(x.reshape(3,2))

print("Reshape")
print(torch.reshape(x,(6,1)))
print(x.reshape(6,1))

print("Reshape")
print(torch.reshape(x,(1,6)))
print(x.reshape(1,6))


print('dot')
print(torch.dot(x[0],x[1]))
print(x[0].dot(x[1]))


X : tensor([[1, 2, 3],
        [4, 5, 6]])
Y : tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)
ADD
tensor([[ 2.,  4.,  6.],
        [ 8., 10., 12.]], dtype=torch.float64)
tensor([[ 2.,  4.,  6.],
        [ 8., 10., 12.]], dtype=torch.float64)
tensor([[ 2.,  4.,  6.],
        [ 8., 10., 12.]], dtype=torch.float64)
SUBTRACT
tensor([[0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)
tensor([[0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)
tensor([[0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)
MULTIPLY
tensor([[ 1.,  4.,  9.],
        [16., 25., 36.]], dtype=torch.float64)
tensor([[ 1.,  4.,  9.],
        [16., 25., 36.]], dtype=torch.float64)
tensor([[ 1.,  4.,  9.],
        [16., 25., 36.]], dtype=torch.float64)
DIVIDE
tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
POWER
tensor([[1.0000e+00, 4.0

In [167]:
print("Sigmoid")
x,torch.sigmoid(x)

Sigmoid


(tensor([[1, 2, 3],
         [4, 5, 6]]),
 tensor([[0.7311, 0.8808, 0.9526],
         [0.9820, 0.9933, 0.9975]]))

In [168]:
print("ReLU")
x,torch.relu(x)

ReLU


(tensor([[1, 2, 3],
         [4, 5, 6]]),
 tensor([[1, 2, 3],
         [4, 5, 6]]))

In [169]:
print("Softmax")
x =x.to(torch.float64)
x, torch.softmax(x, dim=0), torch.softmax(x, dim=1)

Softmax


(tensor([[1., 2., 3.],
         [4., 5., 6.]], dtype=torch.float64),
 tensor([[0.0474, 0.0474, 0.0474],
         [0.9526, 0.9526, 0.9526]], dtype=torch.float64),
 tensor([[0.0900, 0.2447, 0.6652],
         [0.0900, 0.2447, 0.6652]], dtype=torch.float64))

# ====================

In [170]:
x = torch.tensor(3.0, requires_grad=True)
y = x ** 2
y.backward()
x.grad
x , y

(tensor(3., requires_grad=True), tensor(9., grad_fn=<PowBackward0>))

In [171]:
x = torch.tensor(3.0, requires_grad=True)
y = x ** 2
z = torch.sin(y)
# y.backward()
z.backward()
x.grad, y.grad, z.grad
# x , y , z

/tmp/ipykernel_1722/274975935.py:6: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more information. (Triggered internally at /pytorch/build/aten/src/ATen/core/TensorBody.h:494.)
  x.grad, y.grad, z.grad


(tensor(-5.4668), None, None)

# ================

In [172]:
x = torch.tensor(6.7)
y = torch.tensor(0.0)

w = torch.tensor(1.0, requires_grad=True)
b = torch.tensor(0.0, requires_grad=True)


In [173]:
w,y,w,b

(tensor(1., requires_grad=True),
 tensor(0.),
 tensor(1., requires_grad=True),
 tensor(0., requires_grad=True))

In [174]:
z = w*x+b
y_pred = torch.sigmoid(z)
loss = -(y*torch.log(y_pred) + (1-y)*torch.log(1-y_pred))

In [175]:
z,y_pred,loss

(tensor(6.7000, grad_fn=<AddBackward0>),
 tensor(0.9988, grad_fn=<SigmoidBackward0>),
 tensor(6.7012, grad_fn=<NegBackward0>))

In [176]:
loss.backward()

In [177]:
w.grad, b.grad

(tensor(6.6918), tensor(0.9988))

# ===============

In [178]:
x = torch.tensor([1.0,2.0,3.0], requires_grad=True)
y = x**2
# y.backward()
x.grad

In [179]:
x = torch.tensor([1.0,2.0,3.0], requires_grad=True)
y1 = (x**2).mean()
y1.backward()
x.grad,x.grad.zero_


(tensor([0.6667, 1.3333, 2.0000]), <function Tensor.zero_>)