In [6]:
import torch
torch.__version__

'2.9.1+cpu'

In [ ]:
x = torch.tensor([1, 2, 3, 4, 5]) #1D tensor
x

tensor([1, 2, 3])

In [9]:
y = torch.tensor([[1, 2, 3], [4, 5, 6]]) #2D tensor
y


tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
torch.zeros(3, 4) #3x4 tensor of all zeros 3 rows and 4 columns

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [11]:
torch.ones(2, 3, 4) #3D tensor with 2 matrices of 3 rows and 4 columns

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [32]:
torch.rand(2, 2) #2x2 tensor with random values between 0 and 1

tensor([[0.9851, 0.9305],
        [0.8384, 0.0667]])

### Implementing Tensors in PyTorch

y = w * x + b

In [34]:
x = torch.tensor([1.,2.,3.,4.,5.])
y = torch.tensor([2.,  4.,  6.,  8., 10.])

In [37]:
w = torch.tensor(0.0)
b = torch.tensor(0.0)

In [42]:
y_pred = w * x + b

In [ ]:
loss = ((y_pred - y)**2).mean()


In [48]:
print("Actual Value",y)
print("Predicted Value",y_pred)
print("Loss:",loss)
print("Loss:",loss.item())

Actual Value tensor([ 2.,  4.,  6.,  8., 10.])
Predicted Value tensor([0., 0., 0., 0., 0.])
Loss: tensor(44.)
Loss: 44.0
